Created binarysearch.cpp
aryangulati/Hacktoberfest2021 pull request #129
Opened 2020-10-17 10:21 UTC by visakh2

2020-10-17 11:39 UTC, ritiksoni00 commented on Projects/binarysearch.cpp
> +#include <iostream>
Add comments!

2020-10-20 06:56 UTC, ritiksoni00 commented on Projects/binarysearch.cpp
> +#include <iostream>
You are supposed to make changes in Files @visakh2. i will close It After 8.00 pm! 
Please Do it!

2020-10-21 18:37 UTC, thevirtualbuddy commented on Projects/binarysearch.cpp
> +	cout<<"Enter the number that you want to search:";
Sort the numbers after taking input from the user

2020-10-21 18:40 UTC, thevirtualbuddy requested changes
Binary Search works only for sorted elements, so either
1. ask the user to input the elements in sorted order (not recommended)
or
2. sort the elements after the user inputs the data (recommended). 

One example where your code fails is shown below:

how many elements would you like to enter?:5
Enter number 1: 1
Enter number 2: 6
Enter number 3: 2
Enter number 4: 99
Enter number 5: 4
Enter the number that you want to search:4
4 not found in the array

2021-10-01 16:45 UTC, closed without merging